[pytest]
testpaths = .                   # busca tests en todo el proyecto
python_files = test_*.py        # archivos que empiecen por test_
python_classes = Test*          # clases que empiecen por Test
python_functions = test_*       # funciones que empiecen por test_
addopts = -v --tb=short         # salida detallada, errores resumidos